2022-06-04 01:32:58,560 ERROR: Exception on /admin/log1 [POST] [in /home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ulrik/Git/Logger/app/admin/routes.py", line 30, in log1
    return render_template('admin/log1.html', form=form, previewform=previewform)
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/templating.py", line 148, in render_template
    return _render(
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/ulrik/Git/Logger/app/templates/admin/log1.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/home/ulrik/Git/Logger/app/templates/admin/control_panel.html", line 1, in top-level template code
    {% extends 'admin/base.html' %}
  File "/home/ulrik/Git/Logger/app/templates/admin/base.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "/home/ulrik/Git/Logger/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block 'doc'
    {%- block html %}
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block 'html'
    {% block body -%}
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block 'body'
    {% block content -%}
  File "/home/ulrik/Git/Logger/app/templates/base.html", line 48, in block 'content'
    {% block app_content %}{% endblock %}
  File "/home/ulrik/Git/Logger/app/templates/admin/base.html", line 22, in block 'app_content'
    <a class="nav_text nav_link" href="{{ url_for('admin.form1') }}">Form1</a>
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/helpers.py", line 336, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/helpers.py", line 323, in url_for
    rv = url_adapter.build(
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/werkzeug/routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'admin.form1'. Did you mean 'admin.log1' instead?
2022-06-04 01:34:29,770 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:58]
2022-06-04 01:34:43,471 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:58]
2022-06-04 01:49:32,968 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:58]
2022-06-04 01:49:35,381 ERROR: Exception on /admin/create_log [GET] [in /home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ulrik/Git/Logger/app/admin/routes.py", line 42, in create_log
    return render_template('admin/create_log.html')
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/templating.py", line 148, in render_template
    return _render(
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/ulrik/Git/Logger/app/templates/admin/create_log.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/home/ulrik/Git/Logger/app/templates/admin/control_panel.html", line 1, in top-level template code
    {% extends 'admin/base.html' %}
  File "/home/ulrik/Git/Logger/app/templates/admin/base.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "/home/ulrik/Git/Logger/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block 'doc'
    {%- block html %}
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block 'html'
    {% block body -%}
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block 'body'
    {% block content -%}
  File "/home/ulrik/Git/Logger/app/templates/base.html", line 48, in block 'content'
    {% block app_content %}{% endblock %}
  File "/home/ulrik/Git/Logger/app/templates/admin/base.html", line 24, in block 'app_content'
    {% block admin_content %}
  File "/home/ulrik/Git/Logger/app/templates/admin/create_log.html", line 7, in block 'admin_content'
    {{ wtf.quick_form(headerForm)}}
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/jinja2/runtime.py", line 777, in _invoke
    rv = self._func(*arguments)
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/wtf.html", line 200, in template
    {{ form.hidden_tag() }}
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'headerForm' is undefined
2022-06-04 01:49:59,810 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:58]
