2022-06-02 02:15:55,310 ERROR: Exception on /user/test [GET] [in /home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask_login/utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/ulrik/Git/Logger/app/main/routes.py", line 29, in user
    return render_template('user.html', user=user)
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/templating.py", line 149, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/templating.py", line 59, in get_source
    return self._get_source_fast(environment, template)
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/templating.py", line 95, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: user.html
2022-06-02 02:16:04,980 ERROR: Exception on /control_panel [GET] [in /home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ulrik/Git/Logger/app/main/routes.py", line 34, in control_panel
    return render_template('control_panel.html', title='Control Panel')
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/templating.py", line 149, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/templating.py", line 59, in get_source
    return self._get_source_fast(environment, template)
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/templating.py", line 95, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: control_panel.html
2022-06-02 02:16:21,729 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:48]
2022-06-02 02:24:55,462 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:48]
2022-06-02 02:30:31,651 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:48]
2022-06-02 02:30:57,181 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:48]
2022-06-02 02:32:39,327 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:48]
2022-06-02 02:37:19,077 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:48]
2022-06-02 02:38:27,694 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:48]
2022-06-02 02:47:29,678 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:48]
2022-06-02 02:49:20,518 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:48]
2022-06-02 02:52:42,896 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:48]
2022-06-02 02:53:14,288 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:48]
